### PR TITLE
Convert `createKnitService` to accept a config callback

### PR DESCRIPTION
**Pull request by srikrsna-buf**
As discussed we update the `createKnitService` to accept a config callback. The API is now similar to `ConnectRouter`.

### CODE REVIEW

**Review by jhump — COMMENTED** [review]
Seems fine. I still don't love removing "add" from the method names, since it seems less clear to read to me. But if this is what idiomatic JS/TS looks like for things like gateways/routers/proxies, alas... 😛 

Holding off on approving because all of the previous discussion about this approach was with @timostamm, so I'd be much more comfortable if he took a look and approved this.

**Comment by paul-sachs** [comment]
I may be missing some context but the API that connect-router uses looks (roughly) like:

```tsx
const router = createConnectRouter().rpc(...).service(...);
// Do something with router
```

This provides us a chainable api so we could theoretically do something like:

```tsx
const routerA = createConnectRouter().rpc(...);
const routerB = routerA.service(...);
// Do something with routerA and routerB separately
```

This change to use `service` over `addService` feels like it doesn't provide the same functionality. If we're looking to match the API of connect-router, would it make more sense to make it chainable instead of a callback?

**Comment by srikrsna-buf** [comment]
@paul-sachs So the current API in practice will look like:
```
createKnitService({
    configure({service}) {
        service(a);
        service(b);
    }
});
```

Do you think chaining is useful here? We don't expose the `Gateway` (yet), do you think we should? I am not sure users will create multiple gateways similar to multiple routers.

**Comment by paul-sachs** [comment]
@srikrsna-buf I guess I'm thinking as a wholistic API, if both connect-router and knit have a similar API mechanism, it's just one less thing to learn. I guess I would prefer that if we're saying we want the APIs to be similar to connect-router that it actually makes sense for that to be the case.

**Review by paul-sachs — APPROVED** [review]

**Pull request merged**
